Hill cipher Explaination
TheAlgorithms/Algorithms-Explanation pull request #102
Opened 2021-05-17 07:26 UTC by Jenil-S

2021-05-17 08:06 UTC, Jenil-S commented
@Panquesito7 Plz review it

2021-05-17 14:37 UTC, Jenil-S commented
@cclauss just review it

2021-05-17 18:04 UTC, Panquesito7 requested changes
👍 Good work.

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +2. Same way convert PT into vector as
```suggestion
2. Same way convert PT into a vector as

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +3. Now we need to encipher the vector by just multiplying these two matrices
```suggestion
3. Now, we need to encipher the vector by just multiplying these two matrices

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +So we will get the encryted text as **POH**
```suggestion
So we will get the encrypted text as **POH**.

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> + ### Decryption
```suggestion
### Decryption

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> + 1. We need to first inverse our key matrix
```suggestion
1. We need to first inverse our key matrix
 
```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +2. For prevoius Cipher Text **POH**
```suggestion
2. For the previous Cipher Text **POH**

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +## Implementation
```suggestion
## Implementation

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +## Video Explanation
```suggestion
## Video Explanation

```

2021-05-17 18:04 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +[A video explanation of hill cipher](https://www.youtube.com/watch?v=6T46sgty4Mk)
```suggestion
[A video explanation of the Hill Cipher](https://www.youtube.com/watch?v=6T46sgty4Mk)
```

2021-05-18 02:46 UTC, Panquesito7 requested changes
Please accept my suggestions mentioned above.

2021-05-18 02:50 UTC, Jenil-S commented
> Please accept my suggestions mentioned above.

I had done all the required changes

2021-05-18 02:51 UTC, Jenil-S commented
> Please accept my suggestions mentioned above.

what else to do??

2021-05-18 05:50 UTC, Jenil-S commented
> Please accept my suggestions mentioned above.

I think now its done you can merge it..

2021-05-18 18:14 UTC, Panquesito7 requested changes

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +As it was invented by Lester.S.Hill,this algorithm was named hill cipher.
```suggestion
As it was invented by Lester.S.Hill, this algorithm was named Hill Cipher.
```

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +## Example
```suggestion
## Example

```

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +1. We have to write key as an `n × n` matrix as
```suggestion
1. We have to write key as an `n × n` matrix as

```

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +2. Same way convert PT into a vector as
```suggestion
2. Same way convert PT into a vector as

```

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +3. Now, we need to encipher the vector by just multiplying these two matrices
```suggestion
3. Now, we need to encipher the vector by just multiplying these two matrices

```

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +### Decryption
```suggestion
### Decryption

```

2021-05-18 18:14 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +2. For the prevoius Cipher Text **POH**
```suggestion
2. For the previous Cipher Text **POH**

```

2021-05-19 04:18 UTC, Panquesito7 commented on en/Ciphers/hill_cipher.md
> +key:`GYBNQKURP`
```suggestion
key:`GYBNQKURP`

```

2021-05-19 04:32 UTC, Panquesito7 submitted a review, later dismissed
Great work, @Jenil-S. LGTM. Thank you for your contribution! 👍 🎉

2021-05-31 08:00 UTC, appgurueu submitted a review, later dismissed
Explanation is fine

2021-05-31 08:20 UTC, cclauss approved these changes

2021-05-31 08:20 UTC, merged