BellNumbers.md
TheAlgorithms/Algorithms-Explanation pull request #189
Opened 2022-10-14 18:14 UTC by shiwanshi

2022-10-14 18:26 UTC, appgurueu requested changes
Please use Markdown. Yes, Markdown is a superset of HTML, but if possible, Markdown is to be preferred. You should be using MD headings, paragraphs & line breaks rather than HTML tags.

2022-10-19 15:36 UTC, appgurueu requested changes
This is still no proper Markdown. Please cut down on the number of blank lines, use headings instead of bold / emphasis, use a code block for the code and perhaps also for the set.

2022-10-21 01:52 UTC, Panquesito7 requested changes

2022-10-21 01:52 UTC, Panquesito7 commented on en/Dynamic Programming/Bell Numbers.md
> +```
```suggestion
```java
```

2022-10-21 01:52 UTC, Panquesito7 commented on en/Dynamic Programming/Bell Numbers.md
> +https://en.wikipedia.org/wiki/Bell_triangle
```suggestion
### References

- <https://en.wikipedia.org/wiki/Bell_number>
- <https://en.wikipedia.org/wiki/Bell_triangle>
```

2022-10-24 19:36 UTC, Panquesito7 requested changes

2022-10-24 19:36 UTC, Panquesito7 commented on en/Dynamic Programming/Bell Numbers.md
> +- <https://en.wikipedia.org/wiki/Bell_triangle>
```suggestion
- [Bell Number - Wikipedia](https://en.wikipedia.org/wiki/Bell_number)
- [Bell Triangle - Wikipedia](https://en.wikipedia.org/wiki/Bell_triangle)
```

2022-10-24 19:36 UTC, Panquesito7 commented on en/Dynamic Programming/Bell Numbers.md
> +### Examples:
```suggestion
# BELL NUMBERS

## Number of ways to Partition a Set

Given a set of n elements, find number of ways of partitioning it.
## Examples

```

2022-10-24 19:36 UTC, Panquesito7 commented on en/Dynamic Programming/Bell Numbers.md
> +### Recommended practice
```suggestion
```

## Recommended practice

```

2022-10-28 23:31 UTC, Panquesito7 requested changes

2022-10-28 23:31 UTC, Panquesito7 commented on en/Dynamic Programming/Bell Numbers.md
> +Below is Dynamic Programming based implementation of the above recursive code using the Stirling number-
There's missing spaces here. Also, I think you need to end the codeblock before all the text.

2022-12-06 01:09 UTC, closed without merging