Added the explanation for Sorting algorithm ( Find Second largest element )
TheAlgorithms/Algorithms-Explanation pull request #198
Opened 2022-10-23 18:18 UTC by siva-balan

2022-10-23 18:27 UTC, appgurueu requested changes
1. Your headers should not additionally be in bold;
2. Typography: Add a space after a colon (`:`), but not before it; add a space before `(`, but not after it or before `)`.
3. Phrasing: Try less technical phrasing for the approach (something like "first find & store the largest element by looping over the array once and keeping track of the largest element seen so far, then loop over the array a second time to find the second largest element as the largest element smaller than the first largest element")
4. This is not a sorting, but rather a "selection" algorithm (selecting the second largest element)

2022-10-24 06:24 UTC, siva-balan commented
The changes are done and I have uploaded the algorithm under selection algorithm

2022-10-25 19:00 UTC, Panquesito7 requested changes

2022-10-25 19:00 UTC, Panquesito7 commented on en/Selection Algorithms/Find Second Largest Element.md
> +```
This is to prevent Markdown Linting errors.
```suggestion
```txt
```

2022-10-25 19:00 UTC, Panquesito7 commented on en/Selection Algorithms/Find Second Largest Element.md
> +[ Java Script ](https://github.com/TheAlgorithms/JavaScript/blob/master/Sorts/FindSecondLargestElement.js)
```suggestion
- [JavaScript](https://github.com/TheAlgorithms/JavaScript/blob/master/Sorts/FindSecondLargestElement.js)
```

2022-10-25 19:00 UTC, Panquesito7 commented on en/Selection Algorithms/Find Second Largest Element.md
> +[ Video explaining 2 approachs ](https://www.youtube.com/watch?v=Mv8jhYQEbkA)
```suggestion
[Video explaining 2 approaches](https://www.youtube.com/watch?v=Mv8jhYQEbkA)
```

2022-10-25 20:31 UTC, Panquesito7 commented on en/Selection Algorithms/Find Second Largest Element.md
> +-  Worst case: `O(n)`
```suggestion
- Best case: `O(n)`
- Average case: `O(n)`
- Worst case: `O(n)`
```

2022-10-28 19:50 UTC, Panquesito7 approved these changes
Looks good. Thanks! 🎉

2022-10-28 21:18 UTC, appgurueu approved these changes

2022-10-28 23:37 UTC, merged