Vigenere Cipher Explanation added in English language
TheAlgorithms/Algorithms-Explanation pull request #210
Opened 2023-03-25 14:55 UTC by JahnabDutta

### Description

Provided the explanation for vignere cipher in the cipher directory of the English language. Added brief encryption and decryption algorithm along with an example. Then described the complexity analysis of the scheme. Furthermore, added resources about regarding the cryptanalysis(attack) of the cipher and caution regarding not using it for real life purposes. 
Also attached the implementation links in python, C++ and javascript. 

### Checklist

- [x] A description of the changes in this PR is mentioned above.
- [x] All the new and existing checks pass.
- [x] No plagiarized, duplicated, or repetitive documentation that has been directly copied from another source.
- [x] If it's a new explanation, it contains solid, understandable, and accessible information.
- [x] I have read the whole [contributing guidelines](https://github.com/TheAlgorithms/Algorithms-Explanation/blob/master/CONTRIBUTING.md) and agree to the [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md).

2023-03-25 16:39 UTC, appgurueu commented on en/Ciphers/vignere_cipher.md
> +3. Once key is found, we can use [frequency analysis](https://en.wikipedia.org/wiki/Frequency_analysis) to crack the cipher.
Once the *key length* is found.

2023-03-25 16:40 UTC, appgurueu reviewed
Otherwise seems to be fine content-wise. Should perhaps point out the relation to the Caeser Cipher?

2023-03-25 17:10 UTC, JahnabDutta commented
Made changes and also added fixed spelling errors.

2023-03-25 18:52 UTC, appgurueu approved these changes
I've now done a pass to fix typos and improve the formatting and wording a bit.

2023-03-28 04:04 UTC, Panquesito7 requested changes

2023-03-28 04:04 UTC, Panquesito7 commented on en/Ciphers/vigenere_cipher.md
> +It is easy to encrypt and decrypt but at the same time, it is easy to intercept and crack this cipher. It is a polyalphabetic substitution cipher, meaning that the same letter of the alphabet can be
```suggestion
It is easy to encrypt and decrypt but at the same time, it is easy to intercept and crack this cipher. It is a polyalphabetic substitution cipher, meaning that the same letter of the alphabet can be replaced by different letters depending on the key. The key is a word or phrase that is repeated to match the length of the message. Then the letters of the key are used to shift the letters of the message.
```

2023-03-28 04:04 UTC, Panquesito7 commented on en/Ciphers/vigenere_cipher.md
> +The Vigenere cipher is an improvement over the Caesar cipher. The Caesar cipher uses a single character as the key to shift the message. In contrast, the Vigenere cipher uses a word or a phrase as th
```suggestion
The Vigenere cipher is an improvement over the Caesar cipher. The Caesar cipher uses a single character as the key to shifting the message. In contrast, the Vigenere cipher uses a word or a phrase as the key. This means that the same character occurring at different positions in the message will be shifted by different amounts. This makes it harder to crack the cipher.
```

2023-03-28 04:04 UTC, Panquesito7 commented on en/Ciphers/vigenere_cipher.md
> +- [Python](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/ciphers/vigenere_cipher.cpp)
Links seem to be inverted.
```suggestion
- [C++](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/ciphers/vigenere_cipher.cpp)
- [Python](https://github.com/TheAlgorithms/Python/blob/master/ciphers/vigenere_cipher.py)
```

2023-03-28 06:55 UTC, appgurueu commented on en/Ciphers/vigenere_cipher.md
> +The Vigenere cipher is an improvement over the Caesar cipher. The Caesar cipher uses a single character as the key to shift the message. In contrast, the Vigenere cipher uses a word or a phrase as th
I think "shift" is fine here.

2023-03-28 06:56 UTC, appgurueu approved these changes

2023-03-28 19:53 UTC, Panquesito7 approved these changes
Thanks! 🚀

2023-03-28 19:54 UTC, merged